### ISSUE TITLE
Improve the git remote command

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/java-assignment-solution-100-01#1]
The `git remote` command should include `.git` at the end of the command, I think.

**Comment by schultzh** [comment]
@gkapfham In the README file? Where should this be fixed?

**Comment by gkapfham** [comment]
Yes, @schultzh this is in the README file.

This is the current command:

```
git remote add download git@github.com:GatorEducator/java-assignment-solution-100-01
```

I think that it should be:

```
git remote add download git@github.com:GatorEducator/java-assignment-solution-100-01.git
```
